# This starter covers CI/CD for most use-cases.
# CI - On PR, run `ksd build` to ensure validity.
# CD - On push OR manual queuing, run `ksd sync` to deploy the changes.

# The following action variables should be set:
# - KUSTO_DB_ENDPOINT
# - KUSTO_SYNC_APP_CLIENT_ID
# - TENANT_ID

# The following action secrets should be set:
# - KUSTO_SYNC_APP_CLIENT_SECRET

name: kusto-ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event_name == 'pull_request'' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install ksd
      run: curl <ksd>

    - name: Build
      run: ./ksd build

  sync:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request'' }}
    steps:
    - uses: actions/checkout@v3

    - name: Install ksd
      shell: bash
      run: |
        wget https://github.com/weikanglim/kusto-synced/releases/latest/download/ksd_linux_x86_64.tar.gz
        tar -xzf ksd_linux_x86_64.tar.gz

    - name: Sync
      shell: bash
      run: >
        ./ksd sync
        --endpoint $KUSTO_DB_ENDPOINT
        --client-id $KUSTO_SYNC_APP_CLIENT_ID
        --tenant-id $TENANT_ID
        --client-secret $CLIENT_SECRET
      env:
        CLIENT_SECRET: ${{ secrets.KUSTO_SYNC_APP_CLIENT_SECRET }}
